SELECT DISTINCT e."JOB NUMBER", t1."PLATE FILE NO",  e."DATAFLEX RECNUM ONE", t1."ESTIMATE RECNUM",  
t1."DATAFLEX RECNUM ONE", e."DETAILS1"
FROM SOPlive_dosrun..Estimate e
JOIN SOPlive_dosrun..TICKET1 t1 ON t1."ESTIMATE RECNUM" = e."DATAFLEX RECNUM ONE"
--WHERE e."JOB NUMBER" = 42231
WHERE NOT t1."PLATE FILE NO" = '        '
AND NOT t1."PLATE FILE NO" IS NULL
ORDER BY e."JOB NUMBER" DESC


/*  
SELECT DISTINCT e."JOB NUMBER", t1."PLATE FILE NO",  e."DATAFLEX RECNUM ONE", t1."ESTIMATE RECNUM",  t1."DATAFLEX RECNUM ONE"
FROM SOPlive_dosrun..Estimate e
JOIN SOPlive_dosrun..TICKET1 t1 ON t1."ESTIMATE RECNUM" = e."DATAFLEX RECNUM ONE"
WHERE NOT t1."PLATE FILE NO" = '        '
AND NOT t1."PLATE FILE NO" IS NULL
ORDER BY e."JOB NUMBER" DESC

SELECT DISTINCT e."JOB NUMBER", t1."PLATE FILE NO",  e."DATAFLEX RECNUM ONE", t1."ESTIMATE RECNUM",  t1."DATAFLEX RECNUM ONE"
FROM SOPlive_dosrun..Estimate e
JOIN SOPlive_dosrun..TICKET1 t1 ON t1."ESTIMATE RECNUM" = e."DATAFLEX RECNUM ONE"
WHERE e."JOB NUMBER" = '42756'
--AND t1."PLATE FILE NO" = '123     '
ORDER BY e."JOB NUMBER" DESC

SELECT DISTINCT e."JOB NUMBER", t1."PLATE FILE NO",  e."DATAFLEX RECNUM ONE", t1."ESTIMATE RECNUM",  t1."DATAFLEX RECNUM ONE"
FROM SOPlive_dosrun..Estimate e
JOIN SOPlive_dosrun..TICKET1 t1 ON t1."ESTIMATE RECNUM" = e."DATAFLEX RECNUM ONE"
--ORDER BY e."DATAFLEX RECNUM ONE" DESC
--WHERE NOT t1."PLATE FILE NO" = '        '
ORDER BY e."JOB NUMBER" DESC

SELECT e."DATAFLEX RECNUM ONE", t."PLATE FILE NO"
FROM SOPlive_dosrun..Estimate e
JOIN SOPlive_dosrun..TICKET1 t ON t."ESTIMATE RECNUM" = e."DATAFLEX RECNUM ONE"
--WHERE e."DATAFLEX RECNUM ONE" > 88000 
ORDER BY e."DATAFLEX RECNUM ONE" DESC

SELECT *
FROM SOPlive_dosrun..TICKET1 t
ORDER BY t."DATAFLEX RECNUM ONE" DESC

*/

